firemodels/smv

Build/dem2fds/Makefile, Build/dem2fds/intel_win_64/make_dem2fds.bat, Build/scripts/test_libs.bat, Build/smokeview/intel_win_64/make_smv.bat, Build/smokezip/intel_win_64/make_smokezip.bat, scripts/BUILDprog.bat, scripts/EDIT_build_smokeview.bat, scripts/fds_smv_env.bat
build libraries if needed when building smokeview, smokezip and dem2fds.  make some corrections to the dem2fds build
=> build some build scripts

Source/smokeview/menus.c, Source/smokeview/viewports.c
having trouble with smokebot.  am reverting to try and get back to a working state.  I'll put these changes back when I figure out what is going on.
=> revert 9795a42c show/hide timebar and time label independently

Source/smokeview/c_api.c
Trivial updates to code in lua_api and c_api to match changes elsewhere.
=> Renaming in Lua code to match upstream.

Build/smokeview/intel_linux_64/make_smv.sh, Build/smokeview/intel_osx_64/make_smv.sh, Source/smokeview/IOboundary.c, Source/smokeview/IOzone.c, Source/smokeview/flowfiles.h, Source/smokeview/glui_display.cpp, Source/smokeview/readsmv.c, Source/smokeview/smokeheaders.h, Source/smokeview/smokeviewvars.h, Utilities/Scripts/md5hash.bat, scripts/MAKEdistwingen.bat, scripts/MAKEtestdistwingen.bat, scripts/PACKAGEsmv.bat
these changes are related creating md5 hashes and a fix for displaying boundary files when blockages like on internal lmesh boundaries
=> md5 and boundary file fix

Source/smokeview/callbacks.c, Source/smokeview/getdata.f90, Source/smokeview/getsizes.f90, Source/smokeview/gsmv.f90, Source/smokeview/readsmv.c, Source/smokeview/smokefortheaders.h, Source/smokeview/startup.c
1. correct error in 'd'/CTRL, 'f'/ALT emulation code
2. add GLSL info to .ini file
3. add hook to allow more modern version of OpenGL to be used with OSX version  of Smokeview (getting closer to being able to use the GPU on the Mac!!!)
4. add linkage to fortran routine that determines slice file direction
=> miscellaneous updates

Source/smokeview/IOslice.c, Source/smokeview/callbacks.c, Source/smokeview/getdata.f90, Source/smokeview/getsizes.f90, Source/smokeview/glui_bounds.cpp, Source/smokeview/glui_motion.cpp, Source/smokeview/main.c, Source/smokeview/menus.c, Source/smokeview/options.h, Source/smokeview/readsmv.c, Source/smokeview/smokefortheaders.h, Source/smokeview/smokeheaders.h, Source/smokeview/smokeviewdefs.h, Source/smokeview/smokeviewvars.h, Source/smokeview/startup.c, Source/smokeview/threader.c, Source/smokeview/threader.h, Source/smokeview/update.c
1.  remove some preprocessing directives
2.  add a (commented) directive to add OpenGL support for osx smokeview.  The directive is commented because it is not working yet
3. fix d/CTRL, f/ALT key substitutions , used on the Mac
4.  minor formatting updates to timing output
=> miscellaneous updates detailed in comments below

Build/dem2fds/Makefile, Build/set_path/Makefile, Build/set_path/ms_win_64/make_set_path.bat, Build/smokeview/ms_win_64/make_smv.bat, Source/shared/file_util.c, Source/shared/file_util.h
1.  make file_exist routine more efficiente for LInux and OSX builds of smokeview
2.  corrections to osx and linux dem2fds makefile entries
3.  add MS C/C++ makefile entry and build script for set_path
=> misc updates

Source/shared/file_util.c, Source/shared/isobox.c, Source/shared/string_util.c, Source/smokeview/IOgeometry.c, Source/smokeview/IOiso.c, Source/smokeview/IOobject.c, Source/smokeview/IOpart.c, Source/smokeview/IOslice.c, Source/smokeview/IOsmoke.c, Source/smokeview/IOvolsmoke.c, Source/smokeview/flowfiles.h, Source/smokeview/glui_bounds.cpp, Source/smokeview/menus.c, Source/smokeview/options.h, Source/smokeview/readsmv.c, Source/smokeview/shaders.c, Source/smokeview/smv_geometry.c, Source/smokeview/viewports.c
also convert tabs to spaces in a number of files
=> offset slice position based on value specified in input file

Source/smokeview/IOslice.c
test to see if I can make a change in a topic branch then merge it back to a branch that has changes not commited
=> smokeview source: test commit from a topic branch

Manuals/SMV_Verification_Guide/SMV_Verification_Guide.tex
Proofread by Sean Davis suggested an edit to this section.
=> SMV Documentation

Source/smokeview/c_api.c
=> Lua: update to upstream changes.

Source/smokeview/c_api.c
Match upstream changes. Under pp_LUA directive only.
=> lua: Update to upstream name changes.

Source/smokeview/lua_api.c, Source/smokeview/main.c, Source/smvluacore/smv.lua, Verification/Scripting/tests.sh, Verification/Scripting/tests/movieTest.lua, Verification/Scripting/tests/test1.lua, Verification/Scripting/tests/testIniParser.lua
Minor updates and fixes across lua code, mostly naming and tests.
=> lua: correct return code and update tests.

Build/env2mod/Makefile, Build/env2mod/intel_linux_64/make_env2mod.sh, Build/env2mod/intel_osx_64/make_env2mod.sh, Build/env2mod/intel_win_64/make_env2mod.bat, Source/background/main.c, Source/dem2fds/main.c, Source/env2mod/env2mod.c, Source/env2mod/env2mod.h, Source/env2mod/main.c, Source/env2mod/options.h, Source/hashfile/main.c, Source/set_path/main.c, Source/sh2bat/sh2bat.c, Source/shared/options_common.h, Source/shared/string_util.c, Source/shared/string_util.h, Source/smokediff/main.c, Source/smokeview/main.c, Source/smokezip/main.c, Source/wind2fds/main.c
this pull request add a program named env2mod that converts a bash script into a module file.  this is done by first creating a snapshot of the bash environment using a command such as 'env | sort > file1'  .  Next you run a script (such as Intel's compilervars.sh script) that updates your environment.  Next your run the command 'env | sort> file2' . The program  env2mod then creates a module file by comparing the differences between files file1 and file2.
=> env2mod - preliminary working version

for_bundle/smokeview_de.po
I have translated the missing phrases and revised the old ones to get a consistent overall look.
=> smv bundle: update German translation file

Source/smokeview/glui_motion.cpp
missed this commit in previous pull request
=> smokeview source: remove unused variable declaration

Source/dem2fds/dem_util.c, Source/dem2fds/dem_util.h, Source/dem2fds/main.c
1. fixes subscript error when outputting y coordinates in &OBST lines 
2 adds BUFF_DIST parameter . OBST's within BUFF_DIST of the boundary use surf's with id surf1,
OBST's in the interior of the domain (greater than BUFF_DIST from the boundary) use surf's with id surf2
=> this pull request addresses fds issue 6589

Source/smokeview/c_api.c
Updates to the lua code to match changes from upstream.
=> lua: Match upstream changes.

Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c
A few things were removed from the smokeview code that needed to be removed from the corresponding Lua API.
=> lua: Match upstream (UpdateLIGHTS removal)

Source/smokeview/lua_api.c
There were a few parts of the lua binding code that weren't gnu89 compliant. This fixes those.
=> lua: Update to match C standard.

Manuals/SMV_Technical_Reference_Guide/SMV_Technical_Reference_Guide.tex, Source/smokeview/IOgeometry.c, Source/smokeview/IOiso.c, Source/smokeview/IOslice.c, Source/smokeview/glui_bounds.cpp, Source/smokeview/menus.c, Source/smokeview/readsmv.c, Source/smokeview/smokeheaders.h, Source/smokeview/smokeviewvars.h, Source/smokeview/structures.h
1. adds a preliminary dialog box for specifying isosurface bounds
2. corrects file loading when the script recording option is used 
passed smokebot
=> this pull request

Build/LIBS/gnu_osx_64/make_LIBS.make, Build/LIBS/intel_linux_64/make_LIBS.make, Build/LIBS/intel_osx_64/make_LIBS.make, Build/smokeview/gnu_linux_64/make_smokeview.sh, Build/smokeview/gnu_osx_64/make_smokeview.sh, Build/smokeview/intel_linux_64/make_smokeview.sh, Build/smokeview/intel_osx_64/make_smokeview.sh, Source/smokeview/IOsmoke.c
for some reason lua is not building on  the mac .  I added a all_nolua target for the various LIBS makefiles and used on the mac
=> consolidate LIBS and smokeview makefiles for osx/linux intel makefile targets

Build/smokeview/Makefile
Simple fix to suppress warnings that are ok.
=> mingw: Add -Wno-write-strings

Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c, Source/smvluacore/inioptions.lua
Mostly changed or removed variables. All inside the lua code.
=> lua: Minor variable changes to match upstream

Build/scripts/setopts.sh, Build/smokeview/gnu_linux_64/make_smokeview_db.sh, README.md, Source/shared/stdio_m.c, Source/shared/stdio_m.h, Source/smokeview/IOpart.c, Source/smokeview/IOscript.c, Source/smokeview/IOsmoke.c, Source/smokeview/glui_bounds.cpp, Source/smokeview/main.c, Source/smokeview/menus.c, Source/smokeview/options.h, Source/smokeview/readsmv.c, Source/smokeview/smokeheaders.h, Source/smokeview/smokeviewdefs.h, Source/smokeview/smokeviewvars.h, Source/smokeview/startup.c, Source/smokeview/structures.h, Source/smokeview/update.c, Utilities/Scripts/qsmv.sh, Utilities/Scripts/smokeview.sh, Verification/README.md
running smokeview in the background on the linux cluster.  multiple instances of qsmv.sh can be run on the same case thereby speeding up the process of generating images needed to create an animation
=> this pull request adds a script named qsmv.sh (analogous to qfds.sh) for 

Build/LIBS/intel_osx_64/make_LIBS.sh, Build/scripts/setopts.sh, Build/smokeview/Makefile, Build/smokeview/gnu_osx_64/make_smokeview.sh, Build/smokeview/gnu_osx_64/make_smokeview_db.sh, Build/smokeview/intel_osx_64/make_smokeview.sh, Build/smokeview/intel_osx_64/make_smokeview_db.sh, Source/glui_v2_1_beta/Makefile, Source/glui_v2_1_beta/makelib.sh, Source/smokeview/glui_bounds.cpp, Source/smokeview/glui_clip.cpp, Source/smokeview/glui_colorbar.cpp, Source/smokeview/glui_display.cpp, Source/smokeview/glui_geometry.cpp, Source/smokeview/glui_motion.cpp, Source/smokeview/glui_objects.cpp, Source/smokeview/glui_shooter.cpp, Source/smokeview/glui_stereo.cpp, Source/smokeview/glui_tour.cpp, Source/smokeview/glui_trainer.cpp, Source/smokeview/glui_wui.cpp, Source/smokeview/options.h
smokeview can be built and run on a mac running catalina.   In order to build and run smokeview you need to install XQuartz (there were bugs in the apple supplied vis library I have not been able to fix).  XQuartz provides an X11 environment (same that smokeview uses on a Linux system)
=> this PR makes changes to the smokeview build scripts makefile and smokeview source so that

Manuals/SMV_User_Guide/SMV_User_Guide.tex, Source/smokeview/callbacks.c
you're lucky - T was available!
=> add 'T' keyboard shortcut for toggling timebar time label bewteen s and h:m:s

Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c, Source/smvluacore/inioptions.lua
Updates and fixes to the lua code to sync with recent upstream commits.
=> Update lua engine for variable changes

Source/background/main.c, Source/smokeview/IOgeometry.c, Source/smokeview/IOwui.c, Source/smokeview/main.c, Source/smokeview/menus.c, Source/smokeview/smokeviewvars.h, Source/smokeview/structures.h
in the background program source
=> add smokeview option to display geometry bounding boxes instead of geometry, correct some preprocessing directives 

Source/smokeview/smokeviewvars.h
will have to make further changes to have separate values for each colorbar
=> change fire cutoff temperature to 600C, opacity depth to 3.0 m .  note these are global quantities - apply to all colorbars. 

.github/workflows/build-smv.yml
This PR fixes recent issues with GitHub checks (repos being out of date) but running a repo update each run.
=> CI: Update apt repos

Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c, Source/smokeview/lua_api.h, Source/smvluacore/bounds.lua, Source/smvluacore/camera.lua, Source/smvluacore/inioptions.lua, Source/smvluacore/render.lua, Source/smvluacore/view.lua
Only affects files under the pp_LUA directive
=> Lua update

Source/smokeview/c_api.c
Simply mimics the changes made to the .ini parser in readsmv.c.
=> lua: update c_api.c to match visZonePlane changes

.github/workflows/cmake.yml
This addresses a recent CI issue by updating apt mirrors.
=> CI: Update apt mirros

Manuals/SMV_Technical_Reference_Guide/SMV_Technical_Reference_Guide.tex
=> Fix error in total FED equation as per ticket #943

Source/smokeview/menus.c, Source/smokeview/options.h, Source/smokeview/showscene.c, Source/smokeview/smokeviewdefs.h, Source/smokeview/smokeviewvars.h, Source/smokeview/update.c
note: texture map may be showed/hidden using diaglox entry at :
Dialogs>View>Examine Geometry , Immersed tab
=> show texture maps by default, make TEND=0.0 and TEND>0.0 startup views more consistent

Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c
Remove code deprecated by recent upstream changes.
=> lua: remove volume/tetra object code

Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c, Source/smvluacore/iniparser.lua, Source/smvluacore/load.lua, Source/smvluacore/pl3d.lua, Source/smvluacore/render.lua, Source/smvluacore/smv.lua, Source/smvluacore/ssfparser.lua, Source/smvluacore/view.lua, Verification/Scripting/tests/blockage_view.lua, Verification/Scripting/tests/movieTest.lua, Verification/Scripting/tests/test1.lua, Verification/Scripting/tests/testColorbarColors.lua, Verification/Scripting/tests/testIniParser.lua
* Correct blockages_hide call
* Add method to toggle display of domain outline
* Expose time properties via the view object
* Fix minor warnings and remove some unnecessary code
=> lua: minor API tweaks

Source/smokeview/lua_api.c, Source/smokeview/smokeheaders.h
Addendum to #1602.
- Removes commented code.
- Exposes `ReadCSV` via the headers as `lua_api.c` needs to use it.
=> Lua updates

.github/workflows/cmake.yml, Source/smokeview/lua_api.c, Source/smokeview/lua_api.h
Some systems have Lua 5.1, this supports building Smokeview with Lua 5.1, with some polyfills as necessary.
e.g. this addresses the lack of `LUA_OK` in older versions of Lua.
=> Lua501 support

.github/workflows/cmake.yml
Reinstate pulling in tests data in CI. This also adds some explanatory notes.
=> Reinstate test data

.github/workflows/cmake.yml, .github/workflows/make-scripts.yml
Some very minor updates just to update dependencies for GitHub actions.
=> CI updates

.github/workflows/cmake.yml
This bumps the Intel oneAPI version for Centos 7.
=> ci: change intel version

Source/smokeview/drawGeometry.c
note: commit message in this PR is wrong, PR subject line comment is correct
=> fix plot3d display when a boundary file was previously loaded (blockage faces were not shown)

Source/smokeview/IOgeometry.c, Source/smokeview/IOplot2d.c, Source/smokeview/glui_display.cpp, Source/smokeview/readsmv.c, Source/smokeview/smokeviewvars.h
These changes were applied after reverting commit b3e965207c141ec4ceb6621a9f9c1945b31e92d5.
=> fix problem with 2D plot label display

Build/smokeview/Makefile, Source/glui_v2_1_beta/Makefile, Source/glui_v2_1_beta/glui_spinner.cpp
Glenn is currently running smokebot on this update but requested a PR in the meantime.
=> Update smokeview make to support gcc12

Source/smvq/smvq.c
Add slice id to JSON output from smvq.
=> smvq: output slice id

.clang-format, Source/smokeview/c_api.c, Source/smokeview/c_api.h, Source/smokeview/lua_api.c
=> Set clang-format "SpaceBeforeParens" to Never

Verification/WUI/levelset2.fds, Verification/scripts/WUI_Cases.sh
This is until we finish inter-mesh linking work.
=> SMV Verification: Change mesh in levelset2.fds.

Source/shared/readobject.c, Source/shared/readobject.h, Source/shared/shared_structures.h, Source/smokeview/IOobjects.c, Source/smokeview/smokeheaders.h, Source/smokeview/structures.h
This splits particle geometry/class reading into shared. This just ends up being a modification to readobject.c etc.
=> add UpdatePartClassDepend to readobject.c

Source/shared/shared_structures.h, Source/smokeview/IOboundary.c, Source/smokeview/IOobjects.c, Source/smokeview/IOslice.c, Source/smokeview/callbacks.c, Source/smokeview/colortimebar.c, Source/smokeview/drawGeometry.c, Source/smokeview/glui_geometry.cpp, Source/smokeview/glui_objects.cpp, Source/smokeview/main.c, Source/smokeview/menus.c, Source/smokeview/readsmv.c, Source/smokeview/showscene.c, Source/smokeview/skybox.c, Source/smokeview/smokeview.c, Source/smokeview/smokeviewvars.h, Source/smokeview/startup.c, Source/smokeview/unit.c, Source/smokeview/update.c, Source/smokeview/viewports.c
There are two commits here:
1. Clean up references to global variables from previous commits.
2. Combine options the control parsing (i.e., `setup_only`, `fast_startup`, etc.) into a single struct and initialise them together,
=> Sweep up some remaining global variables

.github/workflows/cmake.yml
Updates Github actions upload-artifact@v3 -> upload-artifact@v4.
=> ci: update upload-artifact to v4

Source/smokeview/IOgeometry.c, Source/smokeview/IOwui.c, Source/smokeview/callbacks.c, Source/smokeview/glui_display.cpp, Source/smokeview/main.c, Source/smokeview/menus.c, Source/smokeview/options.h, Source/smokeview/readsmv.c, Source/smokeview/showscene.c, Source/smokeview/smokeheaders.h, Source/smokeview/smokeviewvars.h
…don't draw a bounding box around blockages
=> smokeview source: simplify code that hides scene when mouse is down and 

Source/smokeview/IOhvac.c, Source/smokeview/readsmv.c, Source/smokeview/smokeviewvars.h
=> fix to hvac duct value display - addresses smokeview issue #2309
