firemodels/smv

Source/smokeview/IOsmoke.c
Source/smokeview/flowfiles.h
Source/smokeview/glui_3dsmoke.cpp
Source/smokeview/readsmv.c
Source/smokeview/smokeheaders.h
Source/smokeview/smokeviewvars.h

cut off values default to 0.0. Other values can be specified using the 3d smoke dialog box  .
This option is implemented for both 3d smoke and HRRPUV files.  For 3d smoke the cut off values are specified in terms of a smokeview alpha (related to opacity) alpha=0 is completely transparent, alpha=255 completely opaque.  This pull request has passed smokebot.

add  option to not load 3d smoke/hrrpuv files when values are below a specified cutoff value

---

Source/smokeview/IOsmoke.c

this pull request make the recent changes to 3d smoke/hrrpuv sizing code compatible with previous versions of FDS

smokeview source: correction to code that reads 3d smoke/hrrpuv size files (handling max values in a 3d smoke  data frame)

---

Source/smokeview/IOscript.c
Source/smokeview/glui_bounds.cpp
Source/smokeview/options.h

this pull request fixes problem reported in issue 4385.  smokeview was searching all frames except the last one when determining which frame matched a given time

fixes problem with smokeview script keyword SETTIMEVAL

---

Build/smokediff/Makefile
Build/smokeview/Makefile
Build/smokezip/Makefile
Source/shared/isodefs.h
Source/smokediff/options.h
Source/smokediff/svdiff.h
Source/smokeview/main.c
Source/smokeview/options.h
Source/smokeview/smokefortheaders.h
Source/smokeview/startup.c
Source/smokezip/CNVplot3d.c
Source/smokezip/options.h
Source/smokezip/svzip.h

besides cleanup header files, switch logic to use pp_append to add an underscore to Fortran routine names (rather than not adding an underscore if pp_noappend is set).  Set pp_append in the various options.h header rather than in the makefile when pp_LINUX or pp_OSX directives are set
Jake this shouldn't affect you but let me know if it does.

clean up header files

---

Build/smokeview/Makefile
Build/smokeview/gnu_linux_64/make_smokeview.sh
Build/smokeview/gnu_linux_64/make_smokeview_db.sh
Build/smokeview/gnu_osx_64/make_smokeview.sh
Build/smokeview/gnu_osx_64/make_smokeview_db.sh
Source/smokeview/IOobject.c
Source/smokeview/IOslice.c
Source/smokeview/glui_geometry.cpp
Source/smokeview/main.c
Source/smokeview/options.h
Source/smokeview/readsmv.c

1. remove unused variables
2. add -t option to build test gnu osx/linux versions of smokeview
3. remove pp_SLICELOAD preprocessing variable
4. only show immersed geometry dialog box if case has immersed geometry

smokeview cleanup

---

Build/build_smokeview.html
Build/smokeview/intel_win_64/make_smokeview.bat
Source/shared/histogram.h
Source/smokeview/IOboundary.c
Source/smokeview/IOpart.c
Source/smokeview/IOscript.c
Source/smokeview/IOslice.c
Source/smokeview/IOsmoke.c
Source/smokeview/flowfiles.h
Source/smokeview/getdatacolors.c
Source/smokeview/glui_smoke.cpp
Source/smokeview/main.c
Source/smokeview/menus.c
Source/smokeview/options.h
Source/smokeview/readsmv.c
Source/smokeview/smokeheaders.h
Source/smokeview/smokeviewdefs.h
Source/smokeview/smokeviewvars.h
Source/smokeview/startup.c
scripts/webBUILDsmv.bat

1.  eliminates the histogram particle pass .  Now particles are essentially only loaded once instead of 3 times .  I say essentially because the "sizing" pass is now done in C not Fortran which is much quicker because C can skip over the data it doesn't need to know.   For the Gatlinburg case load times that were 2 minutes are now  about 15 seconds.  This addresses issue firemodels/smv#665
2.  Fix problem with Reload/When menu.  This menu is now ignored if selected (addresses issue #6744 )

this pull request

---

Build/smokeview/Makefile

The current code based conforms to the C standard gnu89 (i.e. C89 + GNU extensions), and current build requirments prevent use of C99 features. I would like to add the -std=gnu89 flag to ensure that the builds (and any errors they produced) can be reproduced reliably. This way anyone can compile changes and be sure they will also compile elsewhere (at NIST for example).
This currently only applies gcc as it is the only compiler I can test, but the same flag should be able to be applied to Intel compilers (based on their documentation).
I'm open to suggestions for a more elegant way to do this of course.

Add -std=gnu89 to gcc builds.

---

Build/smokeview/Makefile

gnu89 doesn't work for Intel Windows smokeview builds. It also doesn't work for c++ builds in some situations.  I  moved the use of $(C_STANDARD) to the line defining how to generate .o files.  
I tested Intel/gnu linux and osx builds and intel windows builds
Jake, let me know if there are problems for makefile entries you use

smv build: move C_STANDARD keyword to compiler line

---

Build/smokeview/Makefile

A modification to the mingw build so that libgfortran and libquadmath are statically linked and don't have to be distributed.

mingw: statically link libgfortran

---

Build/smokeview/Makefile

This reintroduces dependencies between the fortran modules to ensure that they're build in the right order. Explicitly specifying these dependencies removes a race condition during build.
This builds successfully as seen here: [https://github.com/JakeOShannessy/smv/actions/runs/1660593294](https://github.com/JakeOShannessy/smv/actions/runs/1660593294).

Reintroduce dependencies between fortran files

---

.github/workflows/build-smv.yml

Given that when the lua build breaks it sends out warnings to others, this commit disables them. At least until a more permanent solution is found.

Remove lua builds

---

.github/workflows/build-smv.yml
Source/smokeview/main.c

The buffer passed to GetOpenFileName (via OpenSMVFile) is `filename_local` and has length `filelength`. However, the memory allocated to `filename_local` is only `len_memory+4`, which is far less than `filelength`. This can cause memory corruption on Windows when longer paths are used.

Correct length of the file buffer passed to GetOpenFilename

---

Tests/get_test_data.ps1
Tests/get_test_data.sh

Now that firemodels/fig has merged the appropriate test data we can use it directly.

Use firemodels/fig repo for test data

---

Source/mergepo/main.c
Source/shared/MALLOCC.h
Source/shared/file_util.c
Source/shared/file_util.h
Source/shared/stdio_buffer.c
Source/shared/string_util.c
Source/smokeview/lua_api.c
Source/smokeview/structures.h

These two header files are no actually necessary in MALLOCC.h. These headers do need to be added elsewhere as they were previously transitively included via MALLOCC.h.
Proposing to merge this to devel2 as it is particularly useful in building tests.

Remove headers mallocc

---

Build/flush/Makefile
Build/makepo/Makefile
Build/mergepo/Makefile
Build/timep/Makefile

This tweaks some linkage of flush, makepo, mergepo, and timep.
The maths library is added to makepo and mergepo.
A Fortran library is removed from flush and timep.

Fix linkage on some ancillary exectuables

---

.github/workflows/cmake.yml
.github/workflows/make-scripts.yml
Tests/get_test_data.sh

Previously, executables other than smokeview were not built using scripts and makefiles. This commit now builds all executables except hashfort.
This will show some failures until #1338 is merged.
(Note this commit only affects Github CI files)

Add other executables

---

Source/shared/options_common.h

Previously if the compiler was not identified as gcc the preprocessor directives forced the assumption that it was an Intel compiler. The Intel preprocessor defines seem to work sufficiently enough for this not to be necessary.
This is mainly for the benefit of MSVC (and also clang).

Don't force Intel compiler by default

---

Source/smokeview/lua_api.c

Previously TrimFront was applied here as a workaround to an
additional space being left in during the parsing progress. This
issue has been resolved and it is no longer necessary.

lua: Remove workaround for issue #1384

---

Source/smokeview/lua_api.c

Took a while to get around to it, smallest PR to date though. The slicedata struct had it's `slicedir` field renamed to `cdir`.

Lua: Update slicedata->slicedir to slicedata->cdir

---

Build/smokeview/Makefile
CMakeLists.txt
Source/smokeview/colortable.c
Source/smokeview/glui_bounds.cpp
Source/smokeview/smokeheaders.h

This is a slight tweak of function locations.
There are two functions (`GetColorTableIndex` and `GetColorTable`)  which are currently in glui_bounds.cpp.  For scripting purposes I've begun building without GLUI, but these two functions are still necessary in other parts of the code.
By having a file dedicated to these colorbar table functions we can compile without GLUI at all (see https://github.com/JakeOShannessy/smv/tree/bypass-glui). This also validates the possibility of moving away from GLUT and GLUI in small steps.

Add colortable.c

---

Source/smokeview/c_api.c
Source/smokeview/c_api.h
Source/smokeview/lua_api.c
Source/smokeview/main.c

Depends on #1593.
I was writing some tests to make sure my changes didn't impact CLI option parsing and -html failed. I notice it doesn't seem to be read anywhere (in contrast to -htmlscript).
Probably just needs removing from the help message.

Remove -html option from help message

---

Build/smokeview/Makefile
CMakeLists.txt
Source/smokeview/command_args.c
Source/smokeview/command_args.h
Source/smokeview/main.c
Source/smokeview/smokeviewdefs.h
Source/smokeview/smokeviewvars.h
Verification/Visualization/CMakeLists.txt

This patch which contains a new CLI parser. This does two important things:
* Disallows the CLI parser from modifying any global variables or otherwise affecting any other parts of the code. This is a first step small step towards reducing the number of global variables.
* Serializes all possible options to a struct which can be documented and type checked.
This might seem like an unimportant reorganisation but will make it easier to do things in the future (next step being clarification of CHID vs filename etc.). This also adds some additional bounds checks.

Factor out CLI parsing into a separate file/module

---

Source/smokeview/colortimebar.c

colortimebar.c uses qsort which comes from stdlib.h.

add stdlib.h for qsort

---

.github/workflows/cmake.yml
CMakeLists.txt
Source/gd-2.0.15/CMakeLists.txt
Source/glui_v2_1_beta/CMakeLists.txt
Source/glut-3.7.6/CMakeLists.txt
Source/jpeg-9b/CMakeLists.txt
Source/lfs/CMakeLists.txt
Source/lpeg/CMakeLists.txt
Source/lua/CMakeLists.txt
Source/png-1.6.21/CMakeLists.txt
Source/pthreads/CMakeLists.txt
Source/smokeview/colortimebar.c
Source/zlib128/CMakeLists.txt

These changes support CMake 3.17, which can be installed on CentOS 7.
This also adds CentOS 7 to GitHub actions.
This depends on #1619.

Adapt CMake to work with older versions

---

Source/smokeview/lua_api.c

Some upstream changes meant that lua versions would crash when run with `-v` and no display attached.
This PR correct that behaviour.

lua: correct lua behaviour with -v

---

CMakeLists.txt
Source/smokeview/IOobjects.c
Source/smokeview/readsmv.c

Smokeview takes configuration settings from a number of locations. This commit comments on these locations and adds two more:
1. Paths defined at compile time. This is used to set paths on various platforms (where config is held in different places).
2. Paths defined as environment variables.

Clarify config paths (smokeview.ini and objects.svo)

---

Source/smokeview/c_api.c
Source/smokeview/c_api.h
Source/smokeview/lua_api.c
Source/smvluacore/view.lua

This PR improves the API around font size handling in lua scripts.
```lua
view.font.size = "small"
view.font.size = "large"
view.font.size = 32
view.font.size = 18
print("Font Size:", view.font.size)
```

lua: improve font size handling in lua scripts

---

Source/smokeview/c_api.c
Source/smokeview/c_api.h
Source/smokeview/callbacks.c
Source/smokeview/lua_api.c
Source/smokeview/lua_api.h
Source/smokeview/main.c

This makes fairly extensive formatting changes to match the style set out in .clang-tidy and .clang-format

lua: refactor to match smv style

---

Source/smokeview/main.c
Source/smokeview/smokeview.c

Many files depend on `smokeview/`main.c as that is where `SMV_EXIT` is defined. Any file which depends on main.c cannot be used anywhere else. With this commit, no other files depend on `smokeview/main.c`.
This is done with the intention of being able to share `ReadSMV` et al. with other programs.

Move SMV_EXIT and StartTimer from main.c

---

Source/shared/md5.c
Source/shared/sha1.c
Source/shared/sha256.c

Very minor change. These files are code for hashing taken from mbedtls, so we probably don't want to be changing them unnecessarily.
This PR just adds comments to that clang-tidy doesn't lint them.

lint: disable linting hash libs

---

.github/workflows/cmake.yml

For some reason the modulefiles path for oneapi has changed. Not sure if this from intel or somewhere else.

ci: fix new modulefiles path

---

CMakeLists.txt
Source/smokeview/lua_api.c
Source/smokeview/main.c
Source/smokeview/startup.c
Tests/.gitignore
Tests/options.h
Tests/parse_smv_benchmark.c
Tests/test_model_large/test_model_large.fds
Tests/test_model_small/test_model_small.fds

Currently, ReadSMV depends on GLUT and GLUI to be able to parse *.smv file (along with fair number of global variables). This PR introduces a new test for *.smv file parsing. This is mainly to demonstrate and test future changes.
There are two other changes:
1. The dependency of lua_api.c on main.c has been removed.
2. `InitStartupDirs()` has been moved up out of `SetupGlut` and placed near the other `Init*` functions. This is so GLUT can be setup without parsing the startup dirs (which is not necessary in the tests for example).

Add parse_smv_benchmark

---

.github/workflows/cmake.yml
Tests/get_test_data.ps1
Tests/get_test_data.sh
Verification/Visualization/thouse5.fds

This fetches a completed FDS run from the fig repo (thouse5) and runs the SSF scripts for it on Github Actions.
Currently it fetches data from a fork of fig, but will be pointed toward firemodels/fig if the PR (https://github.com/firemodels/fig/pull/145) in that repo is merged.
This depends on #1732.

ci: fetch thouse5 from fig and run render tests

---

.github/workflows/cmake.yml
Source/smokeview/smokeviewvars.h
Source/smvq/CMakeLists.txt
Source/smvq/smvq.c

This exposes more information, including surfaces and device activations via the `smvq` binary. This also adds commandline options via getopt.
The only modification is to add `#include GLUT_H` to `smokeviewvars.h` as it is a missing dependency.

Expose more information via smvq

---

.github/workflows/cmake.yml
vcpkg.json

This commit does three things, firstly moves the vcpkg information (i.e., system libraries for Windows) from CI into the repo to ensure consistent usage.
Secondly it disables features of libgd that are not used. One of these features was withdrawn for security reasons by GitHub/Microsoft which caused a build failure.
Thirdly it pins the vcpkg snapshot version so that any if any such withdrawal happens again we'll get a warning from GitHub rather than waiting for the build to fail.

ci: vcpkg: disable default features of libgd

---

CMakeLists.txt

Adding pthreads to some of the shared files introduce pthreads as a new dependency. This is already reflected in the makefiles, this commit adds it to CMakeLists.txt.

cmake: add pthreads dependency to utility programs

---

Source/shared/string_util.c
Source/shared/string_util.h
Source/smokeview/menus.c

`pp_COMPVER` (i.e., what is printed as the compiler version) is defined in the makefile by various scripts. ifdefs fall back to "unknown" otherwise. This also means its not defined when using cmake.
This commit modifies the ifdefs to use compiler defined macros such as `__VERSION__`. This means makes the scripts unnecessary.
The version scripts could be removed from the makefile with this, but I have not done so.

add macro definition for pp_COMPVER

---

Source/shared/string_util.h

A slight tweak to PR #1967 to make the version clearer when using GCC (making it more consistent with Clang and Intel).

tweak pp_COMPVER to be clearer

---

Source/shared/MALLOCC.h
Tests/CMakeLists.txt
Tests/mem_test.c

There were some issues with #include ordering. This test was added to demonstrate that (and make sure the allocator is working in the most basic sense).
MALLOCC.h uses size_t, which was not previously included. This has not arisen previously because size_t has been included for other reasons.
This makes MALLOCC.h independent and doesn't need to be included in any particular order.

Add small memory test

---

Build/smokeview/Makefile
CMakeLists.txt
Source/shared/readlabel.c
Source/shared/readlabel.h
Source/smokeview/glui_display.cpp
Source/smokeview/menus.c
Source/smokeview/output.c
Source/smokeview/readsmv.c
Source/smokeview/showscene.c
Source/smokeview/smokeheaders.h
Source/smokeview/smokeviewvars.h
Source/smokeview/startup.c
Source/smvq/CMakeLists.txt

Move the label functions into shared. Labels are parsed in a *.smv file, therefore the parsing/management code needs to be in shared in order to be able to parse *.smv files without GLUT & GLUI.

split label functions into shared

---

Source/shared/file_util.c
Source/shared/readobject.c
Tests/CMakeLists.txt
Tests/test_root_dir.c

A lot of places in the code assume a trailing slash on the SMV install directory. This ensures that GetSmvRootDir always returns with a trailing slash.
Test included.
This also logs which object files are read as it was the origin of the issue.

add a trailing slash to GetSmvRootDir

---

Build/smokeview/Makefile
CMakeLists.txt
Source/shared/contourdefs.h
Source/shared/readslice.c
Source/shared/readslice.h
Source/shared/shared_structures.h
Source/smokeview/IOscript.c
Source/smokeview/IOslice.c
Source/smokeview/IOvolsmoke.c
Source/smokeview/IOwui.c
Source/smokeview/IOzone.c
Source/smokeview/c_api.c
Source/smokeview/callbacks.c
Source/smokeview/getdatabounds.c
Source/smokeview/getdatacolors.c
Source/smokeview/glui_bounds.cpp
Source/smokeview/glui_display.cpp
Source/smokeview/lua_api.c
Source/smokeview/menus.c
Source/smokeview/readsmv.c
Source/smokeview/renderhtml.c
Source/smokeview/renderimage.c
Source/smokeview/smokeviewvars.h
Source/smokeview/startup.c
Source/smokeview/structures.h
Source/smokeview/unit.c
Source/smokeview/update.c
Source/smokeview/viewports.c
Source/smvq/CMakeLists.txt
Source/smvq/smvq.c

This only moves one function (`GetSliceFileHeader`) as it's the only on necessary to parse a *.smv file.
This also moves the collection of slice data into a struct.

split slice functions and move to shared

---

.github/workflows/cmake.yml

This addresses an issue with the Github actions image possibly not having 7zip (causing actions to fail).

ci: bootstrap vcpkg

---

Source/shared/IOframe.c
Source/shared/dmalloc.c
Source/shared/file_util.c
Source/shared/fopen.c
Source/shared/getdata.c
Source/shared/options_common.h
Source/shared/readgeom.c
Source/shared/smokestream.c
Source/shared/stdio_buffer.c
Source/smokeview/getdatabounds.c

Generally, the shared code (e.g. `dmalloc.c`) uses stderr for logging, but isn't consistent and sometimes stdout is used. This changes all of uses of stdout for logging to stderr within shared/ (and one instance in smokeview/).
This is particularly useful for programs (in particular `smvq`) that outputs data to stdout, allowing us to separate logging from output data. For example `smvq CHID.smv | further-processing | filter > result.json`.

use stderr for logging in shared/

---

Source/shared/readcad.c
Source/shared/readcad.h
Source/shared/readobject.c
Source/shared/readobject.h

This adds `Clear*` functions that allow data structures to be emptied without freeing them. This is useful when allocated as part of larger data structures.

tweak object_collection and cadgeom_collection APIs to be more flexible

---

Source/smokeview/c_api.h
Source/smokeview/lua_api.c
Source/smvq/smvq.c

These are leftovers that weren't fully removed previously. No longer in use.

remove pp_FED code from {c,lua}_api.h

---

Source/smvq/smvq.c

Add vents for each mesh to the output of smvq for further analysis.
Example to list all surfaces used by vents:
```sh
smvq couch.smv | jq .meshes[].vents[].surface_id
```

use smvq to output vent data

---

Source/smokeview/smv_geometry.c
Source/smokeview/update.c

note problem was occurring for all cases.  we just noticed it for the soborot case because the interval between visualization time steps was large.  I'll merge changes after smokebot passes

fix to routine getting time interval when t=tend

---

Source/shared/readcad.c
Tests/CMakeLists.txt
Tests/parse_cad.c

This takes advantage of the CAD geometry file added to the repo to test CAD parsing code during the cmake tests (which run in CI).

add CAD parsing geometry to cmake tests

---

Source/smokeview/readsmv.c

This converts a number of the simpler function in readsmv.c to use `smv_case`.
- `IsDupTexture`
- `IsTerrainTexture`
- `MakeFileLists`
- `Parse*Count and Parse*Process`
- `ParseDevicekeyword`
- `ParseDevicekeyword2`
- `GetInpf`
- `ReadSMV_Init`
- `InitDefaultProp`
- `ReadDeviceHeader`

Remove globals from a series of functions in readsmv.c

---

Source/smokeview/readsmv.c
Tests/CMakeLists.txt
Tests/sort_surfs.c

This also adds a test to ensure sorting works correctly on all platforms. The test is a little verbose can be reduced in size once this function can be moved to shared/.

deglobalise UpdateSortedSurfIdList & SurfIdCompare

---

Source/smokeview/IOgeometry.c
Source/smokeview/IOiso.c
Source/smokeview/IOobjects.c
Source/smokeview/c_api.c
Source/smokeview/callbacks.c
Source/smokeview/drawGeometry.c
Source/smokeview/getdatacolors.c
Source/smokeview/glui_display.cpp
Source/smokeview/menus.c
Source/smokeview/readsmv.c
Source/smokeview/smokeheaders.h
Source/smokeview/smokeviewvars.h
Source/smokeview/startup.c
Source/smvq/smvq.c

#2155 previously overwrote an earlier change during a rebase. This corrects that and produces conforming images when running cad_test.ssf.
I have reviewed the rest of the PR and it only includes `scase`/`global_scase` changes.

correction to PR #2155

---

Source/shared/readobject.c
Source/shared/shared_structures.h
Source/smokeview/IOobjects.c

Objects contained a `use_displaylist` option, however, the parser always sets this to zero and the code is never triggered. This commit removes `use_displaylist` and any code that branches on it.
The use of displaylists has been deprecated in OpenGL so it is unlikely that this is a feature that will be added later.
None of the cases in smokebot trigger displaylists and the only way it would be triggered is if the object definition (e.g. in objects.svo) has no keywords, which doesn't seem possible.
Removing this simplifies things and will allow trimming some other dead code.

remove code for rendering objects with displaylists

---

Source/shared/readobject.c
Source/shared/readobject.h
Source/shared/shared_structures.h
Source/smokeview/menus.c
Source/smokeview/readsmv.c
Tests/parse_objects.c
Tests/test_labels.c
Tests/test_objects.c

As display lists are no longer present, the `use_bw` property of objects is no longer used and can be removed. This also means that `setbw` no longer needs to be passed to the parser.
SETBW as a configuration option works separately.

remove use_bw

---

Source/smokeview/output.c

`__glutFont` is a private function of GLUT and not exposed as part of the API. This causes issues when not building with the vendored GLUT code.
This change instead uses only the functions exposed via the GLUT and GL APIs.

remove references to __glutFont

---

Source/shared/colorbars.h
Source/shared/shared_structures.h
Source/smokeview/IOgeometry.c
Source/smokeview/IOobjects.c
Source/smokeview/IOwui.c
Source/smokeview/c_api.c
Source/smokeview/drawGeometry.c
Source/smokeview/readsmv.c
Source/smokeview/smokeheaders.h
Source/smokeview/smokeviewvars.h
Source/smokeview/startup.c
Tests/sort_surfs.c

Some default colours are hardcoded, but only initilised in the `startup` routine. This commit initialises these values at compile time. This means these values do not rely on startup functions being called in a certain order.
This also moves some color data into smv_case.

initialise hardcoded colour defaults at compile time

---

Source/runbatch/main.c

On Windows, `_access` needs `io.h` (https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/access-waccess?view=msvc-170)

runbatch: add missing include

---

Source/shared/colorbars.c
Source/shared/datadefs.h
Source/shared/readgeom.c
Source/shared/readlabel.c
Source/shared/readlabel.h
Source/shared/readobject.c
Source/shared/readtour.c
Source/shared/shared_structures.h
Source/smokeview/IOobjects.c
Source/smokeview/IOtour.c
Source/smokeview/IOvolsmoke.c
Source/smokeview/getdatacolors.c
Source/smokeview/glui_display.cpp
Source/smokeview/readsmv.c
Source/smokeview/smokeviewdefs.h
Source/smokeview/smokeviewvars.h

This PR does two things:
1. This adds `have_mesh_nabors` and `sky_texture` to shared/ so they can be used without GLUT.
2. Moves a few functions into shared/ and reorders a few lines so that parsing can be moved to shared/.
The only remaining task to be able to parse SMV files without GLUT is to split `readsmv.c` in two. This has been done [here](https://github.com/JakeOShannessy/smv/tree/create-readsmvfile) and I'll propose that as a separate PR.

update smv_case and move a few functions

---

.github/workflows/cmake.yml

Github images updated to cmake 4. On windows this introducing a breaking change, which has since been fixed but means updating the pinned versions.

ci: update vcpkg version

---

Build/smokeview/Makefile
Source/shared/CMakeLists.txt
Source/shared/colorbars.c
Source/shared/file_util.c
Source/shared/file_util.h
Source/shared/paths.c
Source/shared/paths.h
Source/shared/readobject.c
Source/shared/readsmvfile.c
Source/shared/shared_structures.h
Source/smokeview/IOobjects.c
Source/smokeview/command_args.h
Source/smokeview/glui_bounds.cpp
Source/smokeview/glui_motion.cpp
Source/smokeview/main.c
Source/smokeview/menus.c
Source/smokeview/output.c
Source/smokeview/readsmv.c
Source/smokeview/renderimage.c
Source/smokeview/smokeheaders.h
Source/smokeview/smokeview.c
Source/smokeview/startup.c
Source/smvq/smvq.c
Tests/test_root_dir.c

Previously, all paths (including config paths and paths of data files) were initialised into global variables or into a struct. This occurred at various points in the code and did not always use the same logic. If not initialised correctly, smokeview would crash.
This commit places all of this logic into paths.c and uses functions to create paths on demand. This should make the use of paths more consistent. This will also help support things such as different working directories. In many cases a lot of these paths are not used. Whether `fdsprefix` or `chidfilebase` is used is preserved in this commit, but it may be something worth revising as they can be different values.
This also abstracts away much of the buffer and directory separator logic and defers to the underlying OS for that …

Move path definitions to functions

---

Source/shared/shared_structures.h
Source/smokeview/readsmv.c
Source/smokeview/viewports.c

…ue2361""
This reverts commit 3f54d9af9fc67ebddd935608b518f7eb9fae0ced.

change a mesh structure element name (append _smv) to make code clearer (make clear that contents contain smokeview not fds coordinates)

---

.github/workflows/cmake.yml

Previously the macos version was set to macos-latest and was therefore unpinned. This pins the version to macos-14.

ci: pin macos version to macos-14 (arm64)

---

CMakeLists.txt
Source/smokeview/IOscript.c
Tests/CMakeLists.txt
Tests/test_model_small/bad-script.ssf
Tests/test_model_small/good-script.ssf

When an error occurs during RENDERDIR, immediately abort and return a non-zero exit code.
This also adds tests to ensure this works correctly, however, they only run when a display is attached.

abort on script errors

---

Build/background/Makefile
Build/convert/Makefile
Build/env2mod/Makefile
Build/fds2fed/Makefile
Build/flush/Makefile
Build/get_time/Makefile
Build/hashfile/Makefile
Build/makepo/Makefile
Build/mergepo/Makefile
Build/pnginfo/Makefile
Build/set_path/Makefile
Build/sh2bat/Makefile
Build/smokediff/Makefile
Build/smokeview/Makefile
Build/smokezip/Makefile
Build/stars/Makefile
Build/timep/Makefile
Build/wind2fds/Makefile
CMakeLists.txt
Source/scripts/check_code.bat
Source/shared/file_util.c
Source/shared/file_util.h
Source/smokeview/IOslice.c

`X64` is only used on Windows to identify 64-bit platforms, `_WIN64` does the same.
As there currently aren't any 32-bit versions being built it's not likely to be impactful, but theoretically this still supports 32-bit build.

replace X64 with _WIN64

---

Source/smokeview/menus.c
Source/smokeview/renderimage.c

When using the GIF option without loaded data, smokeview renders a static gif (CHID_s0000.gif) but also starts an animated GIF.
This puts the animated GIFs under a branch so that they're only created when data is loaded.

don't render animated GIF with no data loaded
